<RootScreen>:
    MDBottomNavigation:

        MDBottomNavigationItem:
            name: "today screen"
            icon: "calendar"
            text: "Today"

        MDBottomNavigationItem:
            name: "all exercises screen"
            icon: "dumbbell"
            text: "All Exercises"

        MDBottomNavigationItem:
            name: "settings screen"
            icon: "cog"
            text: "settings"